version: "3.6"
services:
  postgres-db:
    build:
      context: ./src/database
      dockerfile: ./postgres.Dockerfile
    env_file:
      - ./src/database/.env
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      grafana-postgres-net:
      speedtest-postgres-net:

  grafana-dash:
    build:
      context: ./src/dashboard
      dockerfile: ./grafana.Dockerfile
    networks:
      grafana-postgres-net:
    ports:
      - 3000:3000

  speedtest:
    build:
      context: ./src/speedtest
      dockerfile: ./speedtest.Dockerfile
    networks:
      speedtest-postgres-net:

volumes:
  postgres:


networks:
  grafana-postgres-net:

  speedtest-postgres-net:
