version: "3.6"
services:
  postgres-db:
    build:
      context: ./src/database
    image: renegademaster/docker-grafana-speedtest-database
    container_name: postgres-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      grafana-postgres-net:
      speedtest-postgres-net:

  grafana-dash:
    build:
      context: ./src/dashboard
    image: renegademaster/docker-grafana-speedtest-dashboard
    container_name: grafana-dash
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      grafana-postgres-net:
    ports:
      - "3000:3000"

  speedtest:
    build:
      context: ./src/speedtest
    image: renegademaster/docker-grafana-speedtest-speedtest
    container_name: speedtest
    restart: always
    networks:
      speedtest-postgres-net:

volumes:
  postgres-data:
  grafana-data:

networks:
  grafana-postgres-net:
  speedtest-postgres-net:
